################################################################
#
# BUILD STEPS
#

################################
#
# JDK base
#
FROM openjdk:11-jdk-slim AS jdk-11-base

RUN apt-get update && \
	apt-get install -y curl && \
	apt-get clean autoclean && \
	apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*



################################
#
# Service Builder
#
FROM jdk-11-base AS service-builder

# setup the build environment
RUN mkdir -p /devel
WORKDIR /devel

COPY ./gradle/wrapper /devel/gradle/wrapper
COPY ./gradlew /devel/

RUN ./gradlew --version

COPY ./settings.gradle /devel/
COPY . /devel/


# build service
RUN ./gradlew :service:bootJar --no-daemon



################################################################
#
# RUN STEPS
#

################################
#
# JRE base
#
FROM openjdk:11-jre-slim AS jre-11-base

RUN apt-get update && \
	apt-get install -y curl && \
	apt-get clean autoclean && \
	apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*


################################
#
# Gateway Runner
#
FROM jre-11-base AS gateway-runner

# setup env
RUN mkdir -p /app/gateway/
WORKDIR /app/gateway

# copy artifacts
COPY --from=gateway-builder /devel/gateway/build/libs/gateway-*.jar ./

# entry point
CMD /bin/bash
