version: '3.4'
# version 3.4. introduces 'target' keyword used in Docker multi-stage builds

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# NLP services                                                              #
#---------------------------------------------------------------------------#
  gate-nlp-drug:
    build:
      context: ..
      target: service-runner-gate
    volumes:
      # configuration files
      - ./config/example-drug:/app/nlp-service/config:ro
      #- ./service/run.sh:/app/nlp-service/run.sh:ro
      # GATE app: example drug app
      - ../resources/gate/drug-app:/gate/app/drug-app:ro
    ports:
      - "8095:8095"
    command: bash /app/nlp-service/run.sh

  gate-nlp-bioyodie:
    build:
      context: ..
      target: service-runner-gate
    volumes:
    # configuration files
    - ./config/bioyodie:/app/nlp-service/config:ro
    # GATE app: bioyodie
    # needs to configure the paths for application and UMLS resources
    - /Users/lroguski/devel/projects/github/bio-YODIE:/gate/app/bioyodie:ro
    - /Users/lroguski/data/UMLS/for-bioyodie/bio-yodie-resources:/gate/app/bioyodie/bio-yodie-resources:ro
    ports:
    - "8096:8095"
    command: bash /app/nlp-service/run.sh
