version: '3.4'
# version 3.4. introduces 'target' keyword used in Docker multi-stage builds

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres container with sample data                                       #
#---------------------------------------------------------------------------#
  gate-nlp:
    build:
      context: ..
      target: service-runner-gate
    volumes:
      # configuration files
      - ./service/config:/app/nlp-service/config:ro
      - ./service/run.sh:/app/nlp-service/run.sh:ro
      # GATE app: example drug app
      - ../resources/gate/drug-app:/gate/app/drug-app:ro
    ports:
      - "8091:8091"
    command: bash /app/nlp-service/run.sh

#---------------------------------------------------------------------------#
# CogStack-Pipeline related containers                                      #
#---------------------------------------------------------------------------#
  gateway:
    build:
      context: ..
      target: gateway-runner
    volumes:
      - ./gateway/config:/app/gateway/config:ro
      - ./gateway/services:/app/gateway/services:ro
      - ./gateway/run.sh:/app/gateway/run.sh:ro
    depends_on:
      - gate-nlp
    ports:
      - "8090:8090"
    command: bash /app/gateway/run.sh
